apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cloudpulse.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.gateway.replicas }}
  # RollingUpdate strategy.
  # maxUnavailable: 0 = always keep all replicas running during a deploy (zero downtime).
  # maxSurge: 1 = spin up 1 extra pod during the update, then remove the old one.
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.selfHealing.gateway.maxSurge }}
      maxUnavailable: {{ .Values.selfHealing.gateway.maxUnavailable }}
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      # restartPolicy: Always means if the container crashes,
      # Kubernetes automatically restarts it. This is the core of self-healing.
      restartPolicy: {{ .Values.selfHealing.restartPolicy }}
      containers:
        - name: gateway
          image: {{ include "cloudpulse.image" .Values.images.gateway }}
          imagePullPolicy: {{ .Values.images.gateway.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.gateway.service.port }}
          envFrom:
            - configMapRef:
                name: cloudpulse-config
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: cloudpulse-secrets
                  key: JWT_SECRET
          {{- include "cloudpulse.livenessProbe" (dict "path" "/healthz" "port" .Values.gateway.service.port) | nindent 10 }}
          {{- include "cloudpulse.readinessProbe" (dict "path" "/healthz" "port" .Values.gateway.service.port) | nindent 10 }}
          resources:
            {{- toYaml .Values.gateway.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: {{ .Values.namespace }}
  labels:
    app: gateway
    {{- include "cloudpulse.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: {{ .Values.gateway.service.port }}
  selector:
    app: gateway
